# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt_name', models.CharField(max_length=100)),
                ('dpt_href', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=100)),
                ('school_href', models.CharField(max_length=150)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=100)),
                ('tutor_href', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=240)),
                ('student', models.CharField(max_length=100)),
                ('dpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='schools.Department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='schools.School')),
            ],
            options={
                'db_table': 'tutors',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpts', to='schools.School'),
        ),
    ]
